# flake/checks/auto-upgrade.nix
# EXTENDED. Signature gate in front of the unattended upgrade. The verify unit
# runs against a local repository and has to refuse an unsigned commit, a commit
# signed by an unlisted key, a signature in the other format, a rollback and an
# unsigned tag, while the verified checkout stays where it was. The VM has no
# network, so nixos-rebuild itself never runs and only the unit wiring is checked.
{
  pkgs,
  inputs,
}: let
  testStubs = {lib, ...}: {
    imports = [
      inputs.self.nixosModules.default
      inputs.home-manager.nixosModules.home-manager
      inputs.disko.nixosModules.disko
      inputs.impermanence.nixosModules.impermanence
      inputs.sops-nix.nixosModules.sops
      {
        options.stylix = lib.mkOption {
          type = lib.types.attrs;
          default = {};
        };
      }
    ];
  };

  # Every key is generated by the test script at run time. The options only
  # name the runtime paths the script writes the public halves to.
  mkNode = verify: {
    imports = [testStubs];
    virtualisation.memorySize = 768;
    environment.systemPackages = [pkgs.git pkgs.gnupg pkgs.openssh];
    othrys.system.autoUpgrade = {
      enable = true;
      verify =
        {
          enable = true;
          url = "file:///srv/hosts.git";
        }
        // verify;
    };
  };
in
  pkgs.testers.runNixOSTest {
    name = "othrys-auto-upgrade-verify";
    node.specialArgs = {inherit inputs;};

    nodes = {
      openpgp = mkNode {
        format = "openpgp";
        publicKeys = ["/run/signers/alice.asc"];
      };
      ssh = mkNode {
        format = "ssh";
        allowedSigners = "/run/signers/allowed_signers";
      };
      tags = mkNode {
        mode = "tag";
        format = "openpgp";
        publicKeys = ["/run/signers/alice.asc"];
      };
    };

    testScript = {nodes, ...}: ''
      import json

      UNIT = "othrys-auto-upgrade-verify.service"
      STATE = "/var/lib/othrys-auto-upgrade-verify"
      FLAKE_URL = "${nodes.openpgp.system.autoUpgrade.flake}".split("#")[0]
      GPG = "GNUPGHOME=/root/gnupg"
      # The subtests start the unit far more often than the daily timer does, so
      # each start first clears the start rate limit of the unit.
      START = f"systemctl reset-failed {UNIT} 2>/dev/null; systemctl start {UNIT}"

      # How a commit or tag gets signed. alice is the listed signer in both
      # formats and mallory is a valid key that no node lists.
      SIGNERS = {
          "pgp-alice": "-c gpg.format=openpgp -c user.signingkey=alice@example.com",
          "pgp-mallory": "-c gpg.format=openpgp -c user.signingkey=mallory@example.com",
          "ssh-alice": "-c gpg.format=ssh -c user.signingkey=/root/ssh/alice",
          "ssh-mallory": "-c gpg.format=ssh -c user.signingkey=/root/ssh/mallory",
      }


      def prepare(node):
          node.start()
          node.wait_for_unit("multi-user.target")
          # The timer must not start a second verification in the middle of a subtest.
          node.succeed("systemctl stop nixos-upgrade.timer")
          node.succeed("mkdir -p /run/signers /root/ssh && install -d -m 700 /root/gnupg")
          for name in ["alice", "mallory"]:
              node.succeed(
                  f'{GPG} gpg --batch --pinentry-mode loopback --passphrase "" '
                  f"--quick-generate-key {name}@example.com ed25519 sign never"
              )
              node.succeed(f'ssh-keygen -q -t ed25519 -N "" -C {name}@example.com -f /root/ssh/{name}')
          node.succeed(f"{GPG} gpg --armor --export alice@example.com > /run/signers/alice.asc")
          node.succeed(
              "echo \"alice@example.com namespaces=\\\"git\\\" $(cat /root/ssh/alice.pub)\" "
              "> /run/signers/allowed_signers"
          )
          node.succeed(
              "git config --global user.name alice",
              "git config --global user.email alice@example.com",
              "git config --global init.defaultBranch main",
              "git init --quiet --bare /srv/hosts.git",
              "git init --quiet /root/work",
              "git -C /root/work remote add origin /srv/hosts.git",
              "echo '{outputs = _: {};}' > /root/work/flake.nix",
              "git -C /root/work add flake.nix",
          )


      def commit(node, message, signer=None):
          how = f"{SIGNERS[signer]} commit -S" if signer else "commit --no-gpg-sign"
          node.succeed(
              f"cd /root/work && {GPG} git {how} --quiet --allow-empty -m '{message}'",
              "git -C /root/work push --quiet --force origin HEAD:main",
          )
          return node.succeed("git -C /root/work rev-parse HEAD").strip()


      def tag(node, name, signer=None, annotate=True):
          how = f"{SIGNERS[signer]} tag -s -m {name}" if signer else ("tag -a -m " + name if annotate else "tag")
          node.succeed(
              f"cd /root/work && {GPG} git {how} {name}",
              f"git -C /root/work push --quiet origin refs/tags/{name}",
          )


      def verified(node):
          return node.succeed(f"git -C {STATE}/checkout rev-parse HEAD").strip()


      def refused(node, reason, still):
          node.fail(START)
          node.succeed("journalctl --sync")
          log = node.succeed(
              f"journalctl -o cat _SYSTEMD_INVOCATION_ID=$(systemctl show -p InvocationID --value {UNIT})"
          )
          assert reason in log, f"expected '{reason}' in: {log}"
          assert verified(node) == still, "a refused ref moved the verified checkout"


      def commit_mode(node, listed, unlisted, other, other_format_reason):
          prepare(node)

          with subtest("a commit signed by the listed key is checked out"):
              first = commit(node, "first", listed)
              node.succeed(START)
              assert verified(node) == first
              assert node.succeed(f"cat {STATE}/last-verified").strip() == first

          with subtest("the flake ref of the rebuild resolves to the verified commit"):
              meta = json.loads(node.succeed(
                  "nix --extra-experimental-features 'nix-command flakes' --offline "
                  f"flake metadata --json {FLAKE_URL}"
              ))
              assert meta["revision"] == first, meta

          with subtest("an unsigned commit is refused"):
              commit(node, "unsigned")
              refused(node, "is not signed", first)

          with subtest("a commit signed by an unlisted key is refused"):
              commit(node, "unlisted", unlisted)
              refused(node, "has no good signature from a configured key", first)

          with subtest("a commit signed in the other format is refused"):
              commit(node, "other format", other)
              refused(node, other_format_reason, first)

          with subtest("a rollback is refused until the state file is removed"):
              latest = commit(node, "latest", listed)
              node.succeed(START)
              assert verified(node) == latest
              node.succeed(
                  f"git -C /root/work reset --quiet --hard {first}",
                  "git -C /root/work push --quiet --force origin HEAD:main",
              )
              refused(node, f"delete {STATE}/last-verified", latest)
              node.succeed(f"rm {STATE}/last-verified", START)
              assert verified(node) == first

          with subtest("the same commit verifies again"):
              node.succeed(START)
              assert verified(node) == first

          with subtest("the upgrade requires and follows the verify unit"):
              wiring = node.succeed("systemctl show nixos-upgrade.service -p Requires -p After")
              requires, after = [
                  next(line for line in wiring.splitlines() if line.startswith(key))
                  for key in ["Requires=", "After="]
              ]
              assert UNIT in requires and UNIT in after, wiring

          # The node is done, so it is powered off hard to free its memory before
          # the next one boots.
          node.crash()


      commit_mode(openpgp, "pgp-alice", "pgp-mallory", "ssh-alice", "is not signed in the openpgp format")
      commit_mode(ssh, "ssh-alice", "ssh-mallory", "pgp-alice", "is not signed in the ssh format")

      prepare(tags)

      with subtest("a signed tag on an unsigned commit is checked out"):
          first = commit(tags, "first")
          tag(tags, "v1.9", "pgp-alice")
          tags.succeed(START)
          assert verified(tags) == first

      with subtest("a newer lightweight tag is refused"):
          second = commit(tags, "second")
          tag(tags, "v1.10", annotate=False)
          refused(tags, "is lightweight", first)

      with subtest("a newer annotated tag without a signature is refused"):
          tag(tags, "v1.11")
          refused(tags, "is not signed", first)

      with subtest("a newer tag signed by an unlisted key is refused"):
          tag(tags, "v1.12", "pgp-mallory")
          refused(tags, "has no good signature from a configured key", first)

      with subtest("an old signed tag served under a newer name is refused"):
          tags.succeed("git -C /root/work push --quiet origin refs/tags/v1.9:refs/tags/v1.13")
          refused(tags, "was signed under a different name", first)

      with subtest("the highest tag by version sort wins once it is signed"):
          tags.succeed(
              "for t in v1.10 v1.11 v1.12 v1.13; do"
              " git -C /root/work push --quiet origin :refs/tags/$t; done",
              "git -C /root/work tag -d v1.10",
          )
          tag(tags, "v1.10", "pgp-alice")
          tags.succeed(START)
          assert verified(tags) == second
    '';
  }
