# flake/checks/impermanence.nix
# CORE. Behavioral test for the impermanence invariant, the defining
# principle of the system. Rather than re-implement the wipe algorithm,
# this extracts the ACTUAL script generated by
# modules/system/impermanence.nix (via an isolated evalModules) and runs
# it against a real btrfs volume, where ephemeral root is archived and cleared,
# /persist survives, and snapshots past the retention window are pruned.
{
  pkgs,
  inputs,
}: let
  # Evaluate just the impermanence module with lightweight stubs for the
  # NixOS/othrys options it touches, so no nixpkgs or disko modules needed.
  # Parameterized over users.enable so both the managed-user and headless
  # variants of the generated script are exercised.
  mkWipeEval = usersOn:
    inputs.nixpkgs.lib.evalModules {
      specialArgs = {inherit pkgs;};
      modules = [
        inputs.self.nixosModules.impermanence
        ({lib, ...}: {
          options = {
            boot = lib.mkOption {
              type = lib.types.attrs;
              default = {};
            };
            environment = lib.mkOption {
              type = lib.types.attrs;
              default = {};
            };
            fileSystems = lib.mkOption {
              type = lib.types.attrs;
              default = {};
            };
            systemd = lib.mkOption {
              type = lib.types.attrs;
              default = {};
            };
            assertions = lib.mkOption {
              type = lib.types.listOf lib.types.raw;
              default = [];
            };
            othrys.system.disko.luks.name = lib.mkOption {
              type = lib.types.str;
              default = "cryptroot";
            };
            othrys.system.user.name = lib.mkOption {
              type = lib.types.str;
            };
            othrys.system.users.enable = lib.mkOption {
              type = lib.types.bool;
              default = false;
            };
          };
          config = {
            othrys.system.impermanence.enable = true;
            othrys.system.user.name = "testuser";
            othrys.system.users.enable = usersOn;
          };
        })
      ];
    };
  wipeScriptOf = eval: pkgs.writeShellScript "root-wipe" eval.config.boot.initrd.systemd.services.root-wipe.script;
  wipeScript = wipeScriptOf (mkWipeEval true);
  wipeScriptHeadless = wipeScriptOf (mkWipeEval false);
  # The operator recovery tool the module installs, extracted from the
  # same eval so the test drives the real artifact.
  oldRootsTool = builtins.head (mkWipeEval true).config.environment.systemPackages;
in
  pkgs.testers.runNixOSTest {
    name = "impermanence-root-wipe";

    nodes.machine = {pkgs, ...}: {
      # A spare disk (/dev/vdb) to hold the btrfs root + persist subvolumes.
      virtualisation.emptyDiskImages = [1024];
      environment.systemPackages = [pkgs.btrfs-progs];
    };

    testScript = ''
      machine.start()
      machine.wait_for_unit("multi-user.target")

      # The real script mounts /dev/mapper/cryptroot, so back it with /dev/vdb.
      machine.succeed("mkfs.btrfs -f /dev/vdb")
      machine.succeed("ln -sf /dev/vdb /dev/mapper/cryptroot")

      with subtest("script variants: only the managed-user script touches /persist/home"):
          machine.succeed("grep -q 'persist/home/testuser' ${wipeScript}")
          machine.fail("grep -q 'persist/home' ${wipeScriptHeadless}")

      # Seed the disko-style layout, root + persist subvolumes, plus an
      # old_roots archive holding an ancient root (outside the retention
      # window), a recent one (inside it), and stray non-subvolume
      # entries that a boot script must never delete or trip over.
      machine.succeed("mkdir -p /seed && mount /dev/vdb /seed")
      machine.succeed("btrfs subvolume create /seed/root")
      machine.succeed("btrfs subvolume create /seed/persist")
      machine.succeed("echo ephemeral > /seed/root/scratch")
      machine.succeed("echo durable > /seed/persist/keepme")
      # old_roots as a SUBVOLUME (harsher than the mkdir'd directory the
      # script creates), since the prune loop's non-subvolume guard cannot save
      # it, so only find's -mindepth 1 stands between an aged archive
      # directory and recursive deletion of every archived root.
      machine.succeed("btrfs subvolume create /seed/old_roots")
      machine.succeed("btrfs subvolume create /seed/old_roots/ancient")
      machine.succeed("touch -d '90 days ago' /seed/old_roots/ancient")
      machine.succeed("btrfs subvolume create /seed/old_roots/recent")
      machine.succeed("echo recent-data > /seed/old_roots/recent/data")
      machine.succeed("touch -d '1 day ago' /seed/old_roots/recent")
      machine.succeed("echo stray > /seed/old_roots/strayfile")
      machine.succeed("touch -d '90 days ago' /seed/old_roots/strayfile")
      machine.succeed("mkdir /seed/old_roots/straydir")
      machine.succeed("touch -d '90 days ago' /seed/old_roots/straydir")
      machine.succeed("umount /seed")

      # Run the module's actual boot-wipe script.
      machine.succeed("${wipeScript}")

      machine.succeed("mount /dev/vdb /seed")

      with subtest("ephemeral root is cleared but archived"):
          machine.fail("test -e /seed/root/scratch")
          machine.succeed("ls /seed/old_roots/*/scratch")

      with subtest("persistent state survives untouched"):
          machine.succeed("grep -q durable /seed/persist/keepme")

      with subtest("retention: ancient pruned, recent kept"):
          machine.fail("test -e /seed/old_roots/ancient")
          machine.succeed("grep -q recent-data /seed/old_roots/recent/data")

      with subtest("stray non-subvolume entries are skipped, not deleted"):
          machine.succeed("grep -q stray /seed/old_roots/strayfile")
          machine.succeed("test -d /seed/old_roots/straydir")

      with subtest("per-user persist home dir was recreated"):
          machine.succeed("test -d /seed/persist/home/testuser")

      # Regression: when no root subvolume exists at boot (so no mv
      # refreshes old_roots' mtime) and the old_roots directory itself
      # has aged past the retention window, pruning must NOT select the
      # directory and wipe the whole archive (the find needs -mindepth 1).
      with subtest("aged old_roots dir never becomes a prune candidate"):
          machine.succeed("btrfs subvolume delete /seed/root")
          machine.succeed("touch -d '90 days ago' /seed/old_roots")
          machine.succeed("umount /seed")
          machine.succeed("${wipeScript}")
          machine.succeed("mount /dev/vdb /seed")
          machine.succeed("test -d /seed/old_roots")
          machine.succeed("grep -q recent-data /seed/old_roots/recent/data")

      # Second boot over the same volume. The archive grows and
      # persist stays intact.
      with subtest("script is safe to run on every boot"):
          machine.succeed("umount /seed")
          machine.succeed("${wipeScript}")
          machine.succeed("mount /dev/vdb /seed")
          machine.succeed("grep -q durable /seed/persist/keepme")
          machine.succeed("test -d /seed/persist/home/testuser")
          machine.succeed("umount /seed")

      # Operator recovery, where the old-roots tool lists the archive and
      # copies a file out of a previous root, read-only and copy-out only.
      with subtest("old-roots tool recovers files from a previous boot"):
          snapshots = machine.succeed("${oldRootsTool}/bin/old-roots list").strip().split("\n")
          assert len(snapshots) >= 1, f"expected archived roots, got {snapshots!r}"
          machine.fail("mountpoint -q /run/old-roots")  # list cleans up its mount
          snap = machine.succeed(
              "${oldRootsTool}/bin/old-roots list | while read -r s; do "
              "  ${oldRootsTool}/bin/old-roots mount >/dev/null; "
              "  if [ -e /run/old-roots/old_roots/$s/scratch ]; then echo $s; fi; "
              "  ${oldRootsTool}/bin/old-roots umount; "
              "done | head -1"
          ).strip()
          assert snap, "no snapshot contains the archived scratch file"
          machine.succeed(f"${oldRootsTool}/bin/old-roots restore {snap} scratch /root/recovered")
          machine.succeed("grep -q ephemeral /root/recovered")
          machine.fail("mountpoint -q /run/old-roots")  # restore cleans up too
    '';
  }
